version: 1.0.{build}
image: Visual Studio 2017
environment:
  INTEGRATION_API_KEY:
    secure: 4uUlTzVCpd9zsz5giAUjy+9+YxwUXDOTBKGMx6VuPEDBp+Ph8OB9/eoZOWESlUutcQReezSFNjwN6px/6k3wzw5w6bk1IWiHsb9o1sE7g6v0+Id9kc/r9m6Jn8IDAbaKQxjlTA0KtJE8wMgucE/VlTCxpHefMU5DSZYQfmF72Oc=
before_build:
  - dotnet --info
  - dotnet restore
build_script:
  - dotnet build
test_script:
  - dotnet test
after_test:
  - dotnet pack -o package
artifacts:
  - path: 'package\*.nupkg'
# deploy:
#   provider: NuGet
#   api_key:
#     secure: TODO
#   skip_symbols: true
#   artifact: 'package\*.nupkg'
#   on:
#     branch: master
#     appveyor_repo_tag: true
